<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserApiTest extends TestCase
{

    use RefreshDatabase;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();
    }

    public function testLoginuserTest(){
        $responce = $this->actingAs($this->user)->json('GET', route('user'));
        $responce
            ->assertStatus(200)
            ->assertJson([
                'name' => $this->user->name
            ]);
    }

    public function testNotLoginuserTest(){
        $responce = $this->json('GET', route('user'));
        $responce->assertStatus(200);
        $this->assertEquals("", $responce->content());
    }
}
